server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authDB
    username: root
    password: banko1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
 secret: pX6r4kz3e2l9f5aD1cB8v7gN0jM5qW2yL4iH9oP3uK6tF1xZ0
 expiration: 3600000
