server:
  port: 9004

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.sikawofie.notificationservice.event.OrderPlacedEvent
        spring.json.use.type.headers: false
        spring.json.ignore.unknown.properties: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "rolandantwi68@gmail.com"
    password: "banko1234"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
